default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: WARNING
  host: db
  port: 5432
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
  stats_execution_limit: 10

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: gamecritic_production
  username: root
  password: gamecriticrds1012
  host: gamecriticdb.c9xxvrayexac.ap-northeast-1.rds.amazonaws.com
